# Generated by Django 6.0.7 on 2026-09-09 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajlasmaAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=100, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alici_side', to=settings.AUTH_USER_MODEL)),
                ('satici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satici_side', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('gönderilme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gönderici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gönderici_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('mesajlasma_alani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='chat.mesajlasmaalani')),
            ],
        ),
    ]
