# Generated by Django 6.0.7 on 2026-09-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_product_has_video_product_is_bulk_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='secenekler',
            field=models.TextField(blank=True, help_text='Seçenekleri virgülle ayırarak yazın. (Örn: Kırmızı, Mavi, Siyah)', null=True),
        ),
    ]
